Updated yml for workflow

diff --git a/.github/workflows/run-script.yml b/.github/workflows/run-script.yml
--- a/.github/workflows/run-script.yml
+++ b/.github/workflows/run-script.yml
@@ -4,6 +4,23 @@ on:
   push:
     branches:
       - main
+      
+jobs:
+  check-repo:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Check for README.md
+        run: |
+          if [ ! -f README.md ]; then
+            echo "README.md file is missing!"
+            exit 1
+          else
+            echo "README.md file exists!"
+          fi      
 
 jobs:
   check-syntax:
@@ -18,3 +35,5 @@ jobs:
 
     - name: Run Syntax Checker
       run: bash bash-script/syntax-checker-ga.sh
+      
+      
